---
- name: Start a long running task
  hosts: all
  gather_facts: false
  vars:
    autogenie_webhook: "http://localhost:8000/webhooks/awx_callback"
  tasks:
    - name: Delay
      ansible.builtin.pause:
        seconds: 1

    - name: Curl test
      ansible.builtin.command: curl -v --max-time 5 http://192.168.0.6:8000/
      ignore_errors: yes
      register: curl_result

    - name: Show curl test result
      ansible.builtin.debug:
        var: curl_result.stdout_lines

    - name: Show curl test stderr (verbose connection info)
      ansible.builtin.debug:
        var: curl_result.stderr_lines

    - name: Send response to Autogenie
      ansible.builtin.uri:
        url: "{{ autogenie_webhook }}"
        method: POST
        body_format: json
        body:
          "job_id": "{{ awx_job_id }}"
          "status": "success"
          "detail": "This is a test launched by: {{ awx_job_template_name }}"
      run_once: yes
